# environment.yml
name: indecomposables
channels:
  - conda-forge
  - defaults
dependencies:
  # Core scientific Python stack
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib

  # Sage and its dependencies
  - sage

  # Testing and development tools
  - parallel
  - tox
  - pytest
  - pytest-cov
  - flake8
  - black
