[tox]
envlist = tests, lint
skipsdist = True

[testenv:tests]
allowlist_externals =
    sage
passenv =
    SAGE_ROOT
    SAGE_LOCAL
    HOME
commands =
    sage -python -m pytest {posargs}

[testenv:lint]
allowlist_externals =
    flake8
    pyflakes
    ruff
commands =
    flake8 scripts tests --max-line-length=120
    pyflakes scripts tests
    ruff check --select=E9,F63,F7,F82 scripts tests
